FROM public.ecr.aws/lambda/python:3.8 AS build

COPY requirements.txt .
RUN pip install --default-timeout 10000 -r requirements.txt
FROM scratch AS runtime
COPY app/ ./app

COPY --from=build . .

CMD ["app.main.handler"]
